//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarQualification
    {
        public int CarID { get; set; }
        public string CarName { get; set; }
        public Nullable<int> qualificationNumber { get; set; }
        public Nullable<int> UnqualifiedTimes { get; set; }
        public Nullable<double> Qualification { get; set; }
    }
}
