//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMCEntities : DbContext
    {
        public EMCEntities()
            : base("name=EMCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<CarQualification> CarQualification { get; set; }
        public virtual DbSet<CarYearQualification> CarYearQualification { get; set; }
        public virtual DbSet<OriginalRecord> OriginalRecord { get; set; }
        public virtual DbSet<OriginalRecorddetails> OriginalRecorddetails { get; set; }
        public virtual DbSet<OriginalRecordPath> OriginalRecordPath { get; set; }
        public virtual DbSet<path> path { get; set; }
        public virtual DbSet<path_18387> path_18387 { get; set; }
        public virtual DbSet<RegistrationPath> RegistrationPath { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ReportFile> ReportFile { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<taskDetails> taskDetails { get; set; }
    }
}
