//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginalRecord
    {
        public int OriginalRecordID { get; set; }
        public string brand { get; set; }
        public string BrandModel { get; set; }
        public string configure { get; set; }
        public string taskAllName { get; set; }
        public string ModelCarModel { get; set; }
        public string VIN { get; set; }
        public string ResultID { get; set; }
        public string introduce { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string taskNumber { get; set; }
        public string category { get; set; }
    }
}
