//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class path
    {
        public int pathID { get; set; }
        public string AV_LH { get; set; }
        public string AV_LH_img { get; set; }
        public string AV_LH_qualified { get; set; }
        public string AV_LV { get; set; }
        public string AV_LV_img { get; set; }
        public string AV_LV_qualified { get; set; }
        public string AV_RH { get; set; }
        public string AV_RH_img { get; set; }
        public string AV_RH_qualified { get; set; }
        public string AV_RV { get; set; }
        public string AV_RV_img { get; set; }
        public string AV_RV_qualified { get; set; }
        public string AK_LH { get; set; }
        public string AK_LH_img { get; set; }
        public string AK_LH_qualified { get; set; }
        public string AK_LV { get; set; }
        public string AK_LV_img { get; set; }
        public string AK_LV_qualified { get; set; }
        public string AK_RH { get; set; }
        public string AK_RH_img { get; set; }
        public string AK_RH_qualified { get; set; }
        public string AK_RV { get; set; }
        public string AK_RV_img { get; set; }
        public string AK_RV_qualified { get; set; }
        public Nullable<int> OriginalRecordID { get; set; }
    }
}
