//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public Nullable<System.DateTime> ExamTime { get; set; }
        public string DocNumber { get; set; }
        public string DocName { get; set; }
        public string BaseOnStandard { get; set; }
        public string State { get; set; }
        public string ModuleIntroduction { get; set; }
        public string LastThing { get; set; }
    }
}
